"""The `{% icon %}` tag.

Icons are inlined <symbol>s (see `pingpong/_icons.html`, generated by
`scripts/build_icon_sprite.mjs`) referenced through <use>, not <img> tags.

The distinction matters: a Lucide file declares `stroke="currentColor"`, and an
<img> is a separate document with no inherited `color`, so every icon in the app
resolved to black. That was survivable on white surfaces and is invisible on the
overhaul's navy -- and it made it impossible for an icon to take the amber of a
live indicator or the red of an action. A <use> reference inherits colour from
its call site, so `text-ball` on the tag is all an amber icon needs.
"""

from django import template
from django.utils.html import format_html

register = template.Library()

# Sizes the design actually uses, so a call site says what it means rather than
# repeating a Tailwind pair. Anything else can still pass `class=` directly.
SIZES = {
    "sm": "w-4 h-4",
    "md": "w-5 h-5",
    "lg": "w-6 h-6",
}


@register.simple_tag
def icon(name, css="", size="", label=""):
    """Render one icon from the inlined sprite.

    `size` is a shorthand for the Tailwind width/height pair, and is optional
    precisely so a call site that already states its own dimensions in `css`
    does not end up with two conflicting sizes on the same element.

    `label` makes the icon meaningful to a screen reader; without it the icon
    is marked aria-hidden, which is right for the common case where the icon
    sits next to text that already says the same thing.
    """
    classes = f"{SIZES.get(size, '')} {css}".strip()
    if label:
        return format_html(
            '<svg class="{}" role="img" aria-label="{}"><use href="#i-{}"></use></svg>',
            classes,
            label,
            name,
        )
    return format_html(
        '<svg class="{}" aria-hidden="true"><use href="#i-{}"></use></svg>',
        classes,
        name,
    )
