services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pingpong_network

  redis:
    image: redis:7-alpine
    container_name: ttstats_redis_prod
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - pingpong_network

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DJANGO_ENV: prod
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
      - redis
    networks:
      - pingpong_network
      - pangolin

volumes:
  pgdata:
  redis_data_prod:
  static_volume:

networks:
  pingpong_network:
    driver: bridge
  pangolin:
    external: true
