services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pingpong_network

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DJANGO_ENV: prod
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - pingpong_network

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "293:293"
      - "4443:4443" 
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - pingpong_network
      - pangolin

volumes:
  pgdata:
  static_volume:

networks:
  pingpong_network:
    driver: bridge
  pangolin:
    external: true
