services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pingpong_dev
      POSTGRES_USER: pingpong
      POSTGRES_PASSWORD: pingpong
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: ttstats_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env.dev
    volumes:
      - ./ttstats:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  pgdata_dev:
  redis_data_dev:
