services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pingpong_network

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DJANGO_ENV: prod
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
    networks:
      - pingpong_network
      - pangolin

volumes:
  pgdata:
  static_volume:

networks:
  pingpong_network:
    driver: bridge
  pangolin:
    external: true
