"""
Django settings for ttstats project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # `ordinal`: the drawer and the leaderboard say "3rd of 8", not "3".
    'django.contrib.humanize',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django_otp_webauthn',
    'pingpong'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ttstats.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'ttstats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pingpong.context_processors.pingpong_context',
                'pingpong.context_processors.push_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ttstats.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production

# Make sure this exists
STATICFILES_DIRS = [
    BASE_DIR / 'pingpong' / 'static',
]

# Plain storage by default. prod.py swaps in WhiteNoise's hashing manifest
# storage; dev and tests must not use it, because it refuses to resolve any
# file that is not in a manifest built by collectstatic.
#
# Note this is STORAGES, not STATICFILES_STORAGE: Django 5.1 removed the
# latter. It was still spelled the old way here, so it was ignored outright
# on Django 6.0 and production served unhashed, uncompressed files -- a
# deploy could not bust a browser's cache of app.css, whose name never
# changes even though its contents do.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

LOGOUT_REDIRECT_URL = '/pingpong/'
ADMIN_LOGOUT_URL = '/accounts/logout/'

# Session security settings
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Prevent CSRF via cross-site requests
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# CSRF security
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'

# Default email settings (override in prod.py)
DEFAULT_FROM_EMAIL = 'noreply@localhost'

# Authentication backends (for passkey + password login)
AUTHENTICATION_BACKENDS = [
    'django_otp_webauthn.backends.WebAuthnBackend',  # Passkey login
    'django.contrib.auth.backends.ModelBackend',     # Traditional password login
]

# WebAuthn configuration
OTP_WEBAUTHN_RP_NAME = "TTStats"
# RP_ID must be a valid domain (not IP address)
# For development: use 'localhost', for production: use your domain
# Setting to None will auto-detect from request hostname
OTP_WEBAUTHN_RP_ID = "localhost"
OTP_WEBAUTHN_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # Must match RP_ID
]

# Web push (VAPID)
#
# Generate a keypair with `python manage.py generate_vapid_keys` and put the
# two values in the environment. Without them WEBPUSH_ENABLED is False and
# every push call is a no-op -- the app still works, it just falls back to
# email, which is exactly what dev and CI want.
#
# VAPID_PUBLIC_KEY is handed to the browser verbatim, so it is not a secret.
# VAPID_PRIVATE_KEY is, and must never reach a template.
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
# The `sub` claim in the VAPID JWT: how a push service contacts you when your
# sending is misbehaving. Must be a mailto: or https: URL.
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:admin@localhost')
WEBPUSH_ENABLED = bool(VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY)

# PWA identity. Kept in settings rather than hardcoded in the manifest
# template so a fork/rename does not mean editing JSON.
PWA_APP_NAME = 'TTStats'
PWA_APP_SHORT_NAME = 'TTStats'
PWA_APP_DESCRIPTION = 'Table tennis matches, Elo and championships.'
PWA_THEME_COLOR = '#0f172a'
PWA_BACKGROUND_COLOR = '#0f172a'

# Redis Cache Configuration
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'ttstats',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'KEY_PREFIX': 'ttstats',
            'TIMEOUT': 300,
        }
    }