# Generated by Django 6.0 on 2026-01-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_location_alter_match_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='location',
            new_name='location_match',
        ),
    ]
