# Generated by Django 6.0 on 2026-01-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0003_rename_location_match_location_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='location_match',
            new_name='location',
        ),
    ]
