# Generated by Django 6.0 on 2026-01-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0004_rename_location_match_match_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='best_of',
            field=models.IntegerField(default=5, help_text='Best of how many games?'),
        ),
    ]
