# Generated by Django 6.0 on 2026-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0005_alter_match_best_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
