# Generated by Django 6.0 on 2026-01-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_double',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player3', to='pingpong.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player4', to='pingpong.player'),
        ),
    ]
