# Generated by Django 6.0 on 2026-01-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Date of the scheduled match')),
                ('scheduled_time', models.TimeField(help_text='Time of the scheduled match')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_matches_created', to='pingpong.player')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pingpong.location')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_matches_as_player1', to='pingpong.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_matches_as_player2', to='pingpong.player')),
            ],
            options={
                'verbose_name': 'Scheduled Match',
                'verbose_name_plural': 'Scheduled Matches',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
    ]
