# Generated by Django 6.0 on 2026-01-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0010_cleanup_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchconfirmation',
            options={'verbose_name_plural': 'Match Confirmations'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='old_winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_confirmed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_confirmed',
        ),
        migrations.AddField(
            model_name='match',
            name='confirmations',
            field=models.ManyToManyField(related_name='player_matchconfirmations', through='pingpong.MatchConfirmation', to='pingpong.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='pingpong.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='pingpong.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='pingpong.team'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pingpong.team'),
        ),
    ]
