# Generated by Django 6.0 on 2026-01-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0013_scheduledmatch_to_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='elo_peak',
            field=models.IntegerField(default=1500, help_text='All-time highest Elo rating'),
        ),
        migrations.AddField(
            model_name='player',
            name='elo_rating',
            field=models.IntegerField(default=1500, help_text='Current Elo rating'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_for_elo',
            field=models.IntegerField(default=0, help_text='Number of confirmed matches that affected Elo (for new player boost)'),
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField(help_text='Elo before match')),
                ('new_rating', models.IntegerField(help_text='Elo after match')),
                ('rating_change', models.IntegerField(help_text='Elo change (can be negative)')),
                ('k_factor', models.FloatField(help_text='K-factor used in calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='pingpong.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='pingpong.player')),
            ],
            options={
                'verbose_name': 'Elo History',
                'verbose_name_plural': 'Elo Histories',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
