# Generated by Django 6.0 on 2026-01-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0014_player_elo_peak_player_elo_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchconfirmation',
            options={},
        ),
        migrations.AlterField(
            model_name='scheduledmatch',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_matches_as_team1', to='pingpong.team'),
        ),
        migrations.AlterField(
            model_name='scheduledmatch',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_matches_as_team2', to='pingpong.team'),
        ),
    ]
