# Generated by Django 6.0 on 2026-02-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0015_alter_matchconfirmation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmatch',
            name='match',
            field=models.OneToOneField(blank=True, help_text='Linked match if this scheduled match was converted to a played match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_from', to='pingpong.match'),
        ),
    ]
