# Generated by Django 6.0 on 2026-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0016_scheduledmatch_match_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score_cache',
            field=models.IntegerField(default=0),
        ),
    ]
