# Generated by Django 6.0 on 2026-02-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0016_scheduledmatch_match_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Championship name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Championship description and rules')),
                ('championship_type', models.CharField(choices=[('singles', 'Singles (1v1)'), ('doubles', 'Doubles (2v2)')], default='singles', help_text='Singles or Doubles championship', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Public championship allow anyone to register. Private championships have fixed participants.')),
                ('max_participants', models.IntegerField(default=8, help_text='Maximum number of participants (players or teams)')),
                ('start_date', models.DateField(help_text='Championship start date')),
                ('end_date', models.DateField(blank=True, help_text='Expected or actual end date', null=True)),
                ('registration_deadline', models.DateField(blank=True, help_text='Last day to register (only for public championships)', null=True)),
                ('status', models.CharField(choices=[('registration', 'Registration Open'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_created', to='pingpong.player')),
                ('location', models.ForeignKey(blank=True, help_text='Default location for championship matches', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pingpong.location')),
                ('participants', models.ManyToManyField(blank=True, help_text='Registered teams/players', related_name='championships', to='pingpong.team')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='championship',
            field=models.ForeignKey(blank=True, help_text='Championship this match belongs to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='pingpong.championship'),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='championship',
            field=models.ForeignKey(blank=True, help_text='Championship this match belongs to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_matches', to='pingpong.championship'),
        ),
    ]
