# Generated by Django 6.0 on 2026-02-05 22:11

from django.db import migrations


def populate_cache_fields(apps, schema_editor):
    """Populate denormalized cache fields for all existing matches."""
    Match = apps.get_model('pingpong', 'Match')
    Game = apps.get_model('pingpong', 'Game')
    MatchConfirmation = apps.get_model('pingpong', 'MatchConfirmation')

    for match in Match.objects.select_related('team1', 'team2').all():
        # Update score caches
        match.team1_score_cache = Game.objects.filter(
            match=match, winner=match.team1
        ).count()
        match.team2_score_cache = Game.objects.filter(
            match=match, winner=match.team2
        ).count()

        # Calculate confirmation status
        # A team is confirmed when all its verified players have confirmed
        team1_verified_ids = set(
            match.team1.players.filter(
                user__profile__email_verified=True
            ).values_list('id', flat=True)
        )
        team2_verified_ids = set(
            match.team2.players.filter(
                user__profile__email_verified=True
            ).values_list('id', flat=True)
        )
        confirmed_player_ids = set(
            MatchConfirmation.objects.filter(
                match=match
            ).values_list('player_id', flat=True)
        )

        match.is_confirmed = (
            team1_verified_ids.issubset(confirmed_player_ids) and
            team2_verified_ids.issubset(confirmed_player_ids)
        )

        match.save(update_fields=[
            'team1_score_cache', 'team2_score_cache', 'is_confirmed'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0017_match_denormalized_cache_fields'),
    ]

    operations = [
        migrations.RunPython(populate_cache_fields, migrations.RunPython.noop),
    ]
