# Generated by Django 6.0 on 2026-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0017_championship_match_championship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'default_manager_name': 'objects', 'ordering': ['-start_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'default_manager_name': 'objects', 'ordering': ['-date_played'], 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='scheduledmatch',
            options={'default_manager_name': 'objects', 'ordering': ['scheduled_date', 'scheduled_time'], 'verbose_name': 'Scheduled Match', 'verbose_name_plural': 'Scheduled Matches'},
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='round_number',
            field=models.IntegerField(blank=True, help_text='Round/matchday number within a championship', null=True),
        ),
    ]
