# Generated by Django 6.0 on 2026-03-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0018_add_round_number_to_scheduledmatch'),
        ('pingpong', '0018_populate_match_cache_fields'),
    ]

    operations = [
    ]
