# Generated by Django 6.0 on 2026-04-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0019_merge_20260309_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('tier', models.CharField(choices=[('none', 'None'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='none', max_length=10)),
                ('group', models.SlugField(max_length=60)),
                ('icon', models.CharField(default='award', max_length=60)),
                ('threshold', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='pingpong.achievement')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_awarded', to='pingpong.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='pingpong.player')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
