# Generated by Django 6.0 on 2026-04-12 14:30

from django.db import migrations


def seed_achievements(apps, schema_editor):
    from pingpong.achievement_definitions import ACHIEVEMENT_DEFINITIONS

    Achievement = apps.get_model('pingpong', 'Achievement')
    for defn in ACHIEVEMENT_DEFINITIONS:
        Achievement.objects.get_or_create(slug=defn['slug'], defaults=defn)


def reverse_seed(apps, schema_editor):
    Achievement = apps.get_model('pingpong', 'Achievement')
    Achievement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0020_achievement_models'),
    ]

    operations = [
        migrations.RunPython(seed_achievements, reverse_seed),
    ]
