# Generated by Django 6.0 on 2026-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0021_seed_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'default_manager_name': 'objects', 'ordering': ['game_number']},
        ),
    ]
