# Generated by Django 6.0 on 2026-05-17 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0022_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='live_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scorekeeper',
            field=models.ForeignKey(blank=True, help_text='Player driving the live scoreboard for this match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_matches', to='pingpong.player'),
        ),
    ]
