# Generated by Django 6.0 on 2026-08-12 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0023_add_live_scoreboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_side',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Side 1'), (2, 'Side 2')], null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_side',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Side 1'), (2, 'Side 2')], db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.PositiveSmallIntegerField(choices=[(1, 'Side 1'), (2, 'Side 2')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pingpong.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='pingpong.player')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'side'], name='pingpong_ma_match_i_f91fb2_idx'), models.Index(fields=['player', 'match'], name='pingpong_ma_player__a797f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='uniq_match_player')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.PositiveSmallIntegerField(choices=[(1, 'Side 1'), (2, 'Side 2')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_match_participations', to='pingpong.player')),
                ('scheduled_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pingpong.scheduledmatch')),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_match', 'side'], name='pingpong_sc_schedul_1dc1f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('scheduled_match', 'player'), name='uniq_scheduled_match_player')],
            },
        ),
    ]
