# Generated by Django 6.0 on 2026-08-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0025_backfill_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional team name for this entry', max_length=100)),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pingpong.championship')),
            ],
            options={
                'verbose_name_plural': 'championship entries',
                'ordering': ['seed', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='side1_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_side1', to='pingpong.championshipentry'),
        ),
        migrations.AddField(
            model_name='match',
            name='side2_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_side2', to='pingpong.championshipentry'),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='side1_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_side1', to='pingpong.championshipentry'),
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='side2_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_as_side2', to='pingpong.championshipentry'),
        ),
        migrations.CreateModel(
            name='ChampionshipEntryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_members', to='pingpong.championship')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pingpong.championshipentry')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_entries', to='pingpong.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'player'), name='uniq_entry_player'), models.UniqueConstraint(fields=('championship', 'player'), name='uniq_championship_player')],
            },
        ),
    ]
