# Generated by Django 6.0 on 2026-08-12 22:04

from django.db import migrations


def _irreversible(apps, schema_editor):
    raise RuntimeError(
        "0028_drop_team cannot be reversed: the Team rows it depended on are "
        "gone and team1_id/team2_id are NOT NULL. Restore a pre-0028 database "
        "snapshot instead."
    )


class Migration(migrations.Migration):
    """Contract step: Team is gone, participants are the only representation.

    This migration is one-way. Reversing it would re-add the NOT NULL
    team1_id/team2_id columns with no values to put in them, so Django's
    auto-reverse fails partway through a table rebuild. The explicit guard
    below turns that into a readable error. To go back, restore a database
    snapshot taken before 0028.
    """

    atomic = True

    dependencies = [
        ('pingpong', '0027_backfill_championship_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            _irreversible,
        ),
    ]
