# Generated by Django 6.0 on 2026-08-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0027_backfill_championship_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
