#!/usr/bin/env node
// Build the inline SVG symbol sheet from the vendored Lucide set.
//
// Why not keep loading them as <img src="...svg">, as the app used to? Because
// every Lucide file declares stroke="currentColor", and an <img> is its own
// document: there is no inherited `color`, so currentColor resolves to black.
// That was invisible-but-survivable on the old white surfaces and is simply
// invisible on the overhaul's navy. It also meant an icon could never take the
// amber of a live indicator or the red of an action.
//
// Inlined <symbol>s referenced by <use href="#i-name"> inherit colour from the
// page, cost one HTTP request instead of fifty, and work under prod's CSP
// (no external fetch, no script).
//
// The OUTPUT IS COMMITTED, on purpose. It is a Django template partial, not a
// build artefact: templates must render correctly from a fresh clone with no
// npm step, exactly as they do today. Re-run this script when adding an icon.
//
//   node scripts/build_icon_sprite.mjs

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconDir = join(root, 'ttstats/pingpong/static/pingpong/icons');
const outFile = join(root, 'ttstats/pingpong/templates/pingpong/_icons.html');

// Only the icons the app actually references. The vendored set is 1600+ files;
// inlining all of them would put half a megabyte on every page render.
// Keep sorted, and keep it in step with `{% icon %}` calls in the templates.
// tests/test_navigation.py::TestIconSprite fails if a template asks for a
// symbol that is not here -- there is no runtime error for that case, the
// icon simply renders as an empty box.
const ICONS = [
  'activity', 'arrow-left', 'arrow-right', 'award', 'badge-check', 'badge-x',
  'bell', 'book-open', 'calendar', 'calendar-check', 'calendar-plus',
  'chart-column', 'chart-spline', 'check', 'check-line',
  'chevron-down', 'chevron-last', 'chevron-left', 'chevron-right',
  'circle-alert', 'circle-check', 'circle-plus', 'circle-x', 'clipboard-list',
  'clock', 'cloud-rain', 'external-link', 'eye', 'file-text', 'flame', 'funnel',
  'hash', 'history', 'info', 'key', 'keyboard', 'layout-dashboard',
  'layout-grid', 'lightbulb', 'list', 'lock', 'log-out', 'map-pin', 'menu',
  'pause', 'pencil', 'play', 'plus', 'rotate-ccw', 'save', 'settings', 'smile',
  'swords', 'trending-down', 'trending-up', 'triangle-alert', 'trophy',
  'undo-2', 'user-plus', 'users', 'wifi-off', 'x', 'zap',
  // Achievement badge glyphs. These are chosen by *data* --
  // achievement_definitions.py stores a Lucide name per achievement -- so they
  // cannot be discovered by scanning the templates. An achievement whose icon
  // is not in the sheet renders an empty box, silently.
  'crown', 'shield', 'star', 'sword', 'target', 'timer',
];

const symbols = [];
for (const name of ICONS) {
  const file = join(iconDir, `${name}.svg`);
  if (!existsSync(file)) {
    console.error(`missing icon: ${name}.svg`);
    process.exitCode = 1;
    continue;
  }
  const svg = readFileSync(file, 'utf8');
  // Everything between the root <svg ...> and </svg>. Lucide files are a flat
  // list of shape elements with no nested <svg>, so a non-greedy match on the
  // first '>' after '<svg' is exact.
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
  const body = inner.replace(/\s+/g, ' ').replace(/>\s</g, '><').trim();
  // stroke-width lives on the symbol rather than the <use> site so an icon
  // scaled to 28px does not come out spindly. The rest (fill/stroke) is
  // inherited from the page, which is the entire point.
  symbols.push(
    `<symbol id="i-${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" ` +
      `stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</symbol>`
  );
}

const out = `{% comment %}
GENERATED by scripts/build_icon_sprite.mjs -- do not edit by hand.

The Lucide icons the app uses, as <symbol>s, included once at the top of
<body> in base.html. Reference them with {% templatetag openblock %} icon "name" {% templatetag closeblock %},
which emits <svg><use href="#i-name"></use></svg> and inherits currentColor.

To add an icon: add its name to ICONS in the build script and re-run
  node scripts/build_icon_sprite.mjs
{% endcomment %}
<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">
${symbols.join('\n')}
</svg>
`;

writeFileSync(outFile, out);
console.log(`wrote ${symbols.length} symbols to ${outFile}`);
